version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxidb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taxidb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
